# to run:
#
# docker run --net host -it \
#   -v /var/lib/zerotier-one/authtoken.secret:/authtoken.secret \
#   -v <token file>:/token.txt \
#   zeronsd:alpine start -s /authtoken.secret -t /token.txt \
#   <network id>

FROM alpine:latest

COPY . /zeronsd
WORKDIR /zeronsd

RUN apk add rust
RUN apk add cargo
RUN apk add openssl
RUN apk add openssl-dev

RUN cargo install --path .

ENV PATH /root/.cargo/bin

ENTRYPOINT ["zeronsd"]
